### ISSUE TITLE
Problems with php7 on MacOS

### ISSUE THREAD

**Issue by matyunin** [phpDocumentor/phpDocumentor2#1735]
I installed `phpdocumentor 2.8.5` from homebrew.  But i can't even start it because i have `Doctrine\Common\Annotations\AnnotationException` error.

There is output:

```
$ phpdoc
PHP Fatal error:  Uncaught Doctrine\Common\Annotations\AnnotationException: You have to enable opcache.load_comments=1 or zend_optimizerplus.load_comments=1. in phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:193
Stack trace:
#0 phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(171): Doctrine\Common\Annotations\AnnotationException::optimizerPlusLoadComments()
#1 phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/vendor/jms/serializer/src/JMS/Serializer/SerializerBuilder.php(338): Doctrine\Common\Annotations\AnnotationReader->__construct()
#2 phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/src/Cilex/Provider/JmsSerializerServiceProvider.php(73): JMS\Serializer\SerializerBuilder->build()
#3 phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/vendor/pimple/pi in phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 193

Fatal error: Uncaught Doctrine\Common\Annotations\AnnotationException: You have to enable opcache.load_comments=1 or zend_optimizerplus.load_comments=1. in phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:193
Stack trace:
#0 phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(171): Doctrine\Common\Annotations\AnnotationException::optimizerPlusLoadComments()
#1 phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/vendor/jms/serializer/src/JMS/Serializer/SerializerBuilder.php(338): Doctrine\Common\Annotations\AnnotationReader->__construct()
#2 phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/src/Cilex/Provider/JmsSerializerServiceProvider.php(73): JMS\Serializer\SerializerBuilder->build()
#3 phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/vendor/pimple/pi in phar:///usr/local/Cellar/phpdocumentor/2.8.5/libexec/phpDocumentor.phar/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 193
```

I enabled `load_comments` in `ext-opcache.ini` but it doesn't help :disappointed: 

```
$ cat /usr/local/etc/php/7.0/conf.d/ext-opcache.ini | grep _comments
opcache.save_comments = 1
opcache.load_comments = 1
```

Can anyone help me?

**Comment by jaapio** [comment]
dupplicates #1701
