### ISSUE TITLE
phpDocumentor won't run on Ubuntu 16.04 LTS with defaults (PHP7)

### ISSUE THREAD

**Issue by g4z** [phpDocumentor/phpDocumentor2#1755]
For me, on a fresh install of latest Ubuntu LTS using the default PHP version, phpDocumentory does not run. I tried .phar download and the Pear install.

Seems like quite a big issue that phpdoc won't run on the latest version of the most popular linux distro.

I'm sure you know, but i don't see a ticket about it!

```
g4z@laptop:~/Downloads$ wget http://phpdoc.org/phpDocumentor.phar
URL transformed to HTTPS due to an HSTS policy
--2016-04-27 10:42:00--  https://phpdoc.org/phpDocumentor.phar
Resolving phpdoc.org (phpdoc.org)... 141.105.126.84
Connecting to phpdoc.org (phpdoc.org)|141.105.126.84|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17089708 (16M) [application/octet-stream]
Saving to: ‘phpDocumentor.phar’

phpDocumentor.phar                            100%[===============================================================================================>]  16.30M  1.36MB/s    in 13s     

2016-04-27 10:42:14 (1.21 MB/s) - ‘phpDocumentor.phar’ saved [17089708/17089708]

g4z@laptop:~/Downloads$ chmod +x phpDocumentor.phar 

g4z@laptop:~/Downloads$ ./phpDocumentor.phar 
PHP Fatal error:  Uncaught Doctrine\Common\Annotations\AnnotationException: You have to enable opcache.load_comments=1 or zend_optimizerplus.load_comments=1. in phar:///home/g4z/Downloads/phpDocumentor.phar/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:193
Stack trace:
#0 phar:///home/g4z/Downloads/phpDocumentor.phar/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(171): Doctrine\Common\Annotations\AnnotationException::optimizerPlusLoadComments()
#1 phar:///home/g4z/Downloads/phpDocumentor.phar/vendor/jms/serializer/src/JMS/Serializer/SerializerBuilder.php(338): Doctrine\Common\Annotations\AnnotationReader->__construct()
#2 phar:///home/g4z/Downloads/phpDocumentor.phar/src/Cilex/Provider/JmsSerializerServiceProvider.php(73): JMS\Serializer\SerializerBuilder->build()
#3 phar:///home/g4z/Downloads/phpDocumentor.phar/vendor/pimple/pimple/lib/Pimple.php(126): Cilex\Provider\JmsSerializerServiceProvider->Cilex\Provider\{closure}(Object(phpDocumentor\Application)) in phar:///home/g4z/Downloads/phpDocumentor.phar/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 193
```

```
g4z@laptop:~/Downloads$ sudo pear channel-discover pear.phpdoc.org
Adding Channel "pear.phpdoc.org" succeeded
Discovery of channel "pear.phpdoc.org" succeeded

g4z@laptop:~/Downloads$ sudo pear install phpdoc/phpDocumentor
downloading phpDocumentor-2.8.5.tgz ...
Starting to download phpDocumentor-2.8.5.tgz (8,184,822 bytes)
... ...done: 8,184,822 bytes
install ok: channel://pear.phpdoc.org/phpDocumentor-2.8.5

g4z@laptop:~/Downloads$ which phpdoc
/usr/bin/phpdoc

g4z@laptop:~/Downloads$ phpdoc
PHP Fatal error:  Uncaught Doctrine\Common\Annotations\AnnotationException: You have to enable opcache.load_comments=1 or zend_optimizerplus.load_comments=1. in /usr/share/php/phpDocumentor/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:193
Stack trace:
#0 /usr/share/php/phpDocumentor/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(171): Doctrine\Common\Annotations\AnnotationException::optimizerPlusLoadComments()
#1 /usr/share/php/phpDocumentor/vendor/jms/serializer/src/JMS/Serializer/SerializerBuilder.php(338): Doctrine\Common\Annotations\AnnotationReader->__construct()
#2 /usr/share/php/phpDocumentor/src/Cilex/Provider/JmsSerializerServiceProvider.php(73): JMS\Serializer\SerializerBuilder->build()
#3 /usr/share/php/phpDocumentor/vendor/pimple/pimple/lib/Pimple.php(126): Cilex\Provider\JmsSerializerServiceProvider->Cilex\Provider\{closure}(Object(phpDocumentor\Application))
#4 /usr/share/php/phpDocumentor/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{cl in /usr/share/php/phpDocumentor/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php on line 193


```

**Comment by jaapio** [comment]
dupplicates #1701
